### ISSUE TITLE
Bug introduced in 2.7.3 - Context's overriddenNonMetaContextVariables member makes it unable to use it concurrently

### ISSUE THREAD

**Issue by sjanel** [HubSpot/jinjava#1212]
Hello,

Our code uses latest version `2.7.3` of **Jinjava**.  There is a new field, in `Context` object, that makes it impossible to share across different threads, causing exceptions when the interpreter `render` method is called:

```java
Caused by: com.hubspot.jinjava.interpret.InterpretException: Error rendering tag
	at com.hubspot.jinjava.tree.TagNode.render(TagNode.java:74)
	at com.hubspot.jinjava.interpret.JinjavaInterpreter.render(JinjavaInterpreter.java:363)
	at com.hubspot.jinjava.interpret.JinjavaInterpreter.render(JinjavaInterpreter.java:307)
	at ...
Caused by: java.util.ConcurrentModificationException: null
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1605)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1628)
	at java.base/java.util.AbstractSet.removeAll(AbstractSet.java:175)
	at com.hubspot.jinjava.interpret.Context.removeNonMetaContextVariables(Context.java:368)
	at com.hubspot.jinjava.lib.tag.ForTag.renderForCollection(ForTag.java:292)
	at com.hubspot.jinjava.lib.tag.ForTag.interpretUnchecked(ForTag.java:155)
	at com.hubspot.jinjava.lib.tag.ForTag.interpret(ForTag.java:120)
	at com.hubspot.jinjava.lib.tag.Tag.interpretOutput(Tag.java:27)
	at com.hubspot.jinjava.tree.TagNode.render(TagNode.java:58)
	... 49 common frames omitted
```

I think that the field `overriddenNonMetaContextVariables` should allow concurrent access, otherwise client code needs to explicitly synchronize calls to `render` for a single top level context which holds this unique instance of this `HashMap` for a whole tree, which is not ideal:

```java
this.overriddenNonMetaContextVariables =
      parent == null ? new HashSet<>() : parent.overriddenNonMetaContextVariables;
```

There is no issue if we revert to `2.7.2` version.

**Comment by sjanel** [comment]
Hello, any news for this ?

**Comment by sjanel** [comment]
Hello ?

**Comment by jasmith-hs** [comment]
@sjanel , fixing with https://github.com/HubSpot/jinjava/pull/1239. This functionality shouldn't be present in the default Jinjava tags.
