### ISSUE TITLE
String splitting does not work

### ISSUE THREAD

**Issue by lycis** [HubSpot/jinjava#52]
When I try to get a part of a string like this (currently using jinjava 2.1.7):

```jinja
{{ repository[0:4] }}
```

I get the following Exception thrown:
```
com.hubspot.jinjava.interpret.TemplateSyntaxException: Property repository is not a sequence.
	at com.hubspot.jinjava.el.ExpressionResolver.resolveExpression(ExpressionResolver.java:74)
	at com.hubspot.jinjava.interpret.JinjavaInterpreter.resolveELExpression(JinjavaInterpreter.java:323)
	at com.hubspot.jinjava.tree.ExpressionNode.render(ExpressionNode.java:41)
	at com.hubspot.jinjava.lib.tag.ForTag.interpret(ForTag.java:137)
	at com.hubspot.jinjava.lib.tag.Tag.interpretOutput(Tag.java:29)
	at com.hubspot.jinjava.tree.TagNode.render(TagNode.java:50)
	at com.hubspot.jinjava.lib.fn.MacroFunction.doEvaluate(MacroFunction.java:69)
	at com.hubspot.jinjava.el.ext.AbstractCallableMethod.evaluate(AbstractCallableMethod.java:72)
	at com.hubspot.jinjava.el.JinjavaInterpreterResolver.invoke(JinjavaInterpreterResolver.java:82)
	at de.odysseus.el.tree.impl.ast.AstMethod.eval(AstMethod.java:91)
	at de.odysseus.el.tree.impl.ast.AstMethod.eval(AstMethod.java:100)
	at de.odysseus.el.tree.impl.ast.AstEval.eval(AstEval.java:51)
	at de.odysseus.el.tree.impl.ast.AstNode.getValue(AstNode.java:31)
	at de.odysseus.el.TreeValueExpression.getValue(TreeValueExpression.java:122)
	at com.hubspot.jinjava.el.ExpressionResolver.resolveExpression(ExpressionResolver.java:62)
	at com.hubspot.jinjava.interpret.JinjavaInterpreter.resolveELExpression(JinjavaInterpreter.java:323)
	at com.hubspot.jinjava.tree.ExpressionNode.render(ExpressionNode.java:41)
	at com.hubspot.jinjava.interpret.JinjavaInterpreter.render(JinjavaInterpreter.java:181)
	at com.hubspot.jinjava.interpret.JinjavaInterpreter.render(JinjavaInterpreter.java:153)
	at com.hubspot.jinjava.Jinjava.renderForResult(Jinjava.java:200)
	at com.hubspot.jinjava.Jinjava.renderForResult(Jinjava.java:173)
	at com.hubspot.jinjava.Jinjava.render(Jinjava.java:149)
	at com.automic.bob.service.translate.parser.jinja.JinjaParser.getParsedString(JinjaParser.java:34)
	at com.automic.bob.service.translate.parser.build.BuildFileParser.parseAction(BuildFileParser.java:186)
	at com.automic.bob.service.translate.parser.build.BuildFileParser.generateScriptForBuildActions(BuildFileParser.java:148)
	at com.automic.bob.service.translate.parser.build.BuildFileParser.parse(BuildFileParser.java:78)
	at com.automic.bob.service.translate.TranslateFileMessageHandler.sendReplyMessage(TranslateFileMessageHandler.java:77)
	at com.automic.bob.service.translate.TranslateFileMessageHandler.handle(TranslateFileMessageHandler.java:42)
	at com.automic.bob.service.translate.TranslateFileMessageHandler.handle(TranslateFileMessageHandler.java:19)
	at com.automic.bob.lib.comm.RabbitMQ$4.handleDelivery(RabbitMQ.java:290)
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:144)
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:99)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.el.ELException: Property repository is not a sequence.
	at com.hubspot.jinjava.el.ext.AstRangeBracket.eval(AstRangeBracket.java:35)
	at de.odysseus.el.tree.impl.ast.AstEval.eval(AstEval.java:51)
	at de.odysseus.el.tree.impl.ast.AstNode.getValue(AstNode.java:31)
	at de.odysseus.el.TreeValueExpression.getValue(TreeValueExpression.java:122)
	at com.hubspot.jinjava.el.ExpressionResolver.resolveExpression(ExpressionResolver.java:62)
	... 34 more
```

**Comment by boulter** [comment]
hi @lycis, string slicing is not currently implemented, but you can split a string into a list and then slice that list. 

Example:

```
{% set repos = repository | list %}
{{ repos[0:3] }}
```

Hope that helps.
