### ISSUE TITLE
Unary minus binds too loosely

### ISSUE THREAD

**Issue by tkindy** [HubSpot/jinjava#893]
Consider the following expression:

```
{{ -1 is integer }}
```

I would expect this to evaluate to `true`, since `-1` is an `integer`. However, this actually throws an error.

```
Exception in thread "main" com.hubspot.jinjava.interpret.FatalTemplateErrorsException: Cannot negate 'class java.lang.Boolean'
	at com.hubspot.jinjava.Jinjava.render(Jinjava.java:192)
	at Scratch.main(scratch.java:6)
```

This implies that the unary minus is binding looser than the `is` operator. That is, Jinjava interprets that expression the same as `-(1 is integer)` when it should interpret it as `(-1) is integer`.

**Comment by tkindy** [comment]
I had to revert #895 while we look into some templates that no longer parse successfully with these changes.
